

hascontrol = 1


//


hsp = 0;
vsp = 0;
grv = 0.5;
walksp = 12;

canjump = 0
canjumppressed = false

c_time = 0

c_time_max = 6

hsp_drift = 1.2
hsp_drift_cutoff = 0.2



//RANDOME NOTE!! ALARMS ACTIVATE CODE INSIDE WHEN THEY REACH 0
//U CAN SET A LOOP BY MAKING IT SET ALARM TO HIGHER NUMBER EVERY TIME IT HITS 0
//INSANELY USEFUL
//ALSO REMMEBER 2 MAKE FOOSTEPS SOUND DIFFERENT ON DIFFERENT MATERIALS
//FUCNION ARRAY OR MAYBE EVEN A SWITCH COULD WORK OR SOME SORT OF COMBO OR ENUM IDKKK
//
//MAKE HORIZONTAL MOVEMENT LESS CHOPPY!!!

/*
MusicPlayer(song.KINDA_SPOOKY)
*/

//MAKE SURE U FIX DA CURSOR IF SHITS WACK!!

//VARS JUST START THIS WAY!!! ITS NOT PERMANENT UNLESS U MAKE IT BE THAT WAY
//LIKE IN A STEP